### PR TITLE
Optimize

### PR DESCRIPTION
**Pull request by cloudskies13**

### CODE REVIEW

**Comment by Fonta22** [comment]
Thanks for the contribution!)

**Comment by cloudskies13** [comment]
np

**Comment by cloudskies13** [comment]
you can make a new release if you want

**Comment by Fonta22** [comment]
I will, after adding some other features 👍🏻

**Comment by Fonta22** [comment]
Done, had to fix a bug about the images. Apparently Tkinter wasn't displaying them because they were declared inside a function or method in this case.

https://github.com/Fonta22/GDTextureRestorer/releases/tag/v1.0.1

**Comment by cloudskies13** [comment]
oh

**Pull request merged**
